/* 
BEGINCOPYRIGHT X,UC
	
	Copyright (c) 2007, Xilinx Inc.
	Copyright (c) 2003, The Regents of the University of California
	All rights reserved.
	
	Redistribution and use in source and binary forms, 
	with or without modification, are permitted provided 
	that the following conditions are met:
	- Redistributions of source code must retain the above 
	  copyright notice, this list of conditions and the 
	  following disclaimer.
	- Redistributions in binary form must reproduce the 
	  above copyright notice, this list of conditions and 
	  the following disclaimer in the documentation and/or 
	  other materials provided with the distribution.
	- Neither the names of the copyright holders nor the names 
	  of contributors may be used to endorse or promote 
	  products derived from this software without specific 
	  prior written permission.
	
	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND 
	CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, 
	INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
	MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
	DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR 
	CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
	SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
	NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
	LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
	HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
	CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
	OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
	SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
	
ENDCOPYRIGHT
*/


//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jul 30 15:39:15 PDT 2004
//----------------------------------------------------

package net.sf.caltrop.cal.parser;

/** CUP generated class containing symbol constants. */
public class CalStatementTerminal {
  /* terminals */
  public static final int QMARK = 94;
  public static final int AT = 17;
  public static final int END_LAMBDA = 39;
  public static final int END_ACTION = 29;
  public static final int TIME = 75;
  public static final int UNDER_SCORE = 100;
  public static final int END_ACTOR = 30;
  public static final int CONST = 20;
  public static final int END_INVARIANT = 38;
  public static final int Character = 3;
  public static final int SEMI = 98;
  public static final int LAMBDA = 58;
  public static final int GUARD = 51;
  public static final int INITIALIZE = 55;
  public static final int RBRACK = 96;
  public static final int COMMA = 82;
  public static final int REQUIRE = 72;
  public static final int RBRACE = 95;
  public static final int VBAR = 101;
  public static final int LBRACK = 90;
  public static final int LT = 92;
  public static final int ALL = 13;
  public static final int DASH_DASH_GT = 83;
  public static final int LBRACE = 89;
  public static final int END_SCHEDULE = 43;
  public static final int ACTION = 11;
  public static final int DASH_GT = 84;
  public static final int END_ASSIGN = 31;
  public static final int FALSE = 46;
  public static final int NOT = 63;
  public static final int MULTI = 61;
  public static final int END_PROC = 41;
  public static final int VAR = 78;
  public static final int THEN = 74;
  public static final int END_BEGIN = 32;
  public static final int UnterminatedCharacter = 9;
  public static final int PROC = 68;
  public static final int PACKAGE = 67;
  public static final int String = 8;
  public static final int SCHEDULE = 73;
  public static final int MOD = 60;
  public static final int PartialOp = 6;
  public static final int TRUE = 77;
  public static final int PLUS = 93;
  public static final int END_CHOOSE = 33;
  public static final int LPAR = 91;
  public static final int WHILE = 79;
  public static final int ASSIGN = 16;
  public static final int END_LET = 40;
  public static final int END_FUNCTION = 35;
  public static final int DO = 25;
  public static final int END_FOREACH = 34;
  public static final int FOR = 47;
  public static final int STAR = 99;
  public static final int DIV = 24;
  public static final int DELAY = 23;
  public static final int ELSE = 27;
  public static final int DOT = 85;
  public static final int PROCEDURE = 69;
  public static final int ACTOR = 12;
  public static final int MAP = 59;
  public static final int Id = 4;
  public static final int NULL = 64;
  public static final int DOM = 26;
  public static final int EOF = 0;
  public static final int RPAR = 97;
  public static final int DEFAULT = 22;
  public static final int Real = 7;
  public static final int FUNCTION = 50;
  public static final int MUTABLE = 62;
  public static final int REPEAT = 71;
  public static final int IMPORT = 53;
  public static final int Integer = 5;
  public static final int CHOOSE = 21;
  public static final int END_IF = 36;
  public static final int INVARIANT = 56;
  public static final int IN = 54;
  public static final int OR = 66;
  public static final int REGEXP = 70;
  public static final int error = 1;
  public static final int IllegalCharacter = 2;
  public static final int SHIFT_THERE = 102;
  public static final int IF = 52;
  public static final int END = 28;
  public static final int COLON = 80;
  public static final int OLD = 65;
  public static final int ANY = 15;
  public static final int FOREACH = 48;
  public static final int END_PROCEDURE = 42;
  public static final int COLON_EQUALS = 81;
  public static final int BEGIN = 19;
  public static final int UnterminatedString = 10;
  public static final int ATN = 18;
  public static final int END_INITIALIZE = 37;
  public static final int FSM = 49;
  public static final int AND = 14;
  public static final int END_WHILE = 44;
  public static final int TO = 76;
  public static final int ENSURE = 45;
  public static final int EQUALS_EQUALS_GT = 87;
  public static final int LET = 57;
  public static final int EQUALS = 86;
  public static final int HASH = 88;
}

