
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 23 15:17:42 PDT 2007
//----------------------------------------------------

package net.sf.caltrop.nl.parser;

/** CUP generated class containing symbol constants. */
public class Terminal {
  /* terminals */
  public static final int QMARK = 93;
  public static final int END_LAMBDA = 40;
  public static final int GT = 86;
  public static final int UNDER_SCORE = 99;
  public static final int TYPE = 15;
  public static final int CONST = 24;
  public static final int END_INVARIANT = 39;
  public static final int NETWORK = 11;
  public static final int Character = 3;
  public static final int SEMI = 97;
  public static final int LAMBDA = 59;
  public static final int GUARD = 53;
  public static final int RBRACK = 95;
  public static final int COMMA = 81;
  public static final int RBRACE = 94;
  public static final int VBAR = 100;
  public static final int LBRACK = 89;
  public static final int LT = 91;
  public static final int ALL = 18;
  public static final int DASH_DASH_GT = 82;
  public static final int LBRACE = 88;
  public static final int END_SCHEDULE = 45;
  public static final int ACTION = 16;
  public static final int DASH_GT = 83;
  public static final int END_ASSIGN = 32;
  public static final int FALSE = 49;
  public static final int NOT = 64;
  public static final int MULTI = 62;
  public static final int END_PROC = 43;
  public static final int VAR = 76;
  public static final int THEN = 73;
  public static final int END_BEGIN = 33;
  public static final int UnterminatedCharacter = 9;
  public static final int PROC = 69;
  public static final int PACKAGE = 68;
  public static final int String = 8;
  public static final int SCHEDULE = 72;
  public static final int MOD = 61;
  public static final int PartialOp = 6;
  public static final int COLON_COLON = 79;
  public static final int TRUE = 75;
  public static final int PLUS = 92;
  public static final int END_CHOOSE = 34;
  public static final int LPAR = 90;
  public static final int WHILE = 77;
  public static final int ASSIGN = 21;
  public static final int END_LET = 41;
  public static final int END_FUNCTION = 36;
  public static final int DO = 28;
  public static final int END_FOREACH = 35;
  public static final int FOR = 50;
  public static final int STAR = 98;
  public static final int DIV = 27;
  public static final int ELSE = 30;
  public static final int DOT = 84;
  public static final int PROCEDURE = 70;
  public static final int ACTOR = 17;
  public static final int MAP = 60;
  public static final int Id = 4;
  public static final int NULL = 65;
  public static final int DOM = 29;
  public static final int EOF = 0;
  public static final int RPAR = 96;
  public static final int DEFAULT = 26;
  public static final int Real = 7;
  public static final int FUNCTION = 52;
  public static final int MUTABLE = 63;
  public static final int REPEAT = 71;
  public static final int IMPORT = 55;
  public static final int Integer = 5;
  public static final int CHOOSE = 25;
  public static final int END_IF = 37;
  public static final int INVARIANT = 57;
  public static final int IN = 56;
  public static final int OR = 67;
  public static final int error = 1;
  public static final int IllegalCharacter = 2;
  public static final int END_PRIORITY = 42;
  public static final int SHIFT_THERE = 101;
  public static final int IF = 54;
  public static final int END = 31;
  public static final int COLON = 78;
  public static final int OLD = 66;
  public static final int ANY = 20;
  public static final int FOREACH = 51;
  public static final int END_PROCEDURE = 44;
  public static final int COLON_EQUALS = 80;
  public static final int BEGIN = 23;
  public static final int UnterminatedString = 10;
  public static final int ENTITIES = 14;
  public static final int ATN = 22;
  public static final int END_INITIALIZE = 38;
  public static final int ENTITY = 13;
  public static final int AND = 19;
  public static final int END_WHILE = 46;
  public static final int TO = 74;
  public static final int STRUCTURE = 12;
  public static final int ENSURE = 47;
  public static final int LET = 58;
  public static final int EQUALS_EQUALS_GT = 48;
  public static final int EQUALS = 85;
  public static final int HASH = 87;
}

